### ISSUE TITLE
Title option from config file is never used

### ISSUE THREAD

**Issue by hannaofsweden** [KidkArolis/jetpack#49]
The 'title' property of the config is not used at all - the title is always taken from the package.json name field, or is 'jetpack' if that does not exist.

In /lib/options.js:
`title: pkg(dir).name || 'jetpack',`

A better way would be:
`title: options.title || pkg(dir).name || 'jetpack',`

**Comment by KidkArolis** [comment]
Fixed in 0.12.2. Thanks for reporting.
