### ISSUE TITLE
Using Jetpack API, setup an ES6 module entry for backend

### ISSUE THREAD

**Issue by znk** [KidkArolis/jetpack#52]
Hello KidkArolis,
My backend is written with `esm` and I would like to have both backend and frontend coexisting. Frontend side was transparent to setup, but I am left wondering how with Jetpack, it should be done to require `esm` to enable ES6 modules in my backend.

Thanks for your project, it is elegant IMHO. And thanks also for your feedback.

**Comment by znk** [comment]
My bad, `jetpack -x 'node -r esm src/server'`.

**Comment by KidkArolis** [comment]
Amazing! Was just typing an answer.

Another option you could try using is the native node 12 esm module support:

```
jetpack -x 'node --experimental-modules src/server'
```

Note that the -x flag simply executes `node .` or the specified exec command (you can put it into `jetpack.config.js#exec`. https://github.com/KidkArolis/jetpack/blob/master/lib/dev.js#L78-L85

Really, it's there for convenience, but most often I find myself executing client and server in 2 different terminal tabs (server with nodemon, client with jetpack) so I get both reloading independently. Although you could also do `jetpack -x `nodemon src/server`.
