### ISSUE TITLE
View webpack.config final output

### ISSUE THREAD

**Issue by SagiMedina** [KidkArolis/jetpack#63]
It would be nice if one can see the final output of the Webpack configuration

**Comment by KidkArolis** [comment]
This is somewhat tricky in principle. There are a few options

a) Show the code that generates config (not the config itself) in a copy/pasteable way such that you could copy this code into your webpack.config.js and start tweaking. This is related to creating unstrap command: https://github.com/KidkArolis/jetpack/issues/5.

b) Show the final generated config (so no loops, conditions, etc. just the final output), but swap in all of the functions (e.g. `include: filepath => !!condition`), classes (e.g. `new Terser`) or other non serialisable JSON things as code strings, somehow.. Tricky.

c) Just print as is using node's util.inspect, which means some things will look like `include: [Function: include],`.

Option c) is the simplest and I while might not be as useful as say a) which you'd use for "ejecting" jetpack, it can still be very useful for debugging issues. So I've added that for now in 0.17.0! E.g.:

```
jetpack -i # for inspect config.. or pr*i*nt config
jetpack --print-config
jetpack --print-config --legacy
jetpack build --print-config
jetpack build --print-config --modern
jetpack build --print-config --legacy
```
<img width="990" alt="image" src="https://user-images.githubusercontent.com/324440/63215455-70f82100-c11e-11e9-99ef-06c1f4f03482.png">

**Comment by KidkArolis** [comment]
Hm, should have maybe named it --show-config, oh well.
