### ISSUE TITLE
Remove "core-js" from alias

### ISSUE THREAD

**Issue by SagiMedina** [KidkArolis/jetpack#64]
Since version 0.16 and above "core-js" set as an alias, that causes an error for libraries like AntD that uses an older version of core-js (core-js@2).

**Comment by KidkArolis** [comment]
It's required for using jetpack from any location, e.g. `jetpack ~/foo`.

But I see how if a library depends on core-js@2, jetpack would break that. Hm..
It is _possible_ to override this in jetpack.config.js by tweaking `delete config.resolve.alias['core-js']`. Not sure what other solution there is.

**Comment by SagiMedina** [comment]
That's a descent solution, it's actually what we are doing for now.l, just thought it worth mentioning but I see your point.

BTW
We mentioned jetpack as our pick for more convenient webpack :)

https://m.facebook.com/AlibabaTechnology/posts/403438563482428?__xts__%5B0%5D=68.ARA1651ymBn9Fk8m63TkaLIpNgZN7RGlox4JM7DnvnUv3VAncx7PhzW3p_31GoiHPYDmEzNXOFuVTqotIB5qSLSTivJ9IE4ws8pvjYUE-kDAWMBGE7BYcvbYIakw5i9y5oy_6DKuNdG70ouQT7GNY3L7XvIFpc67qFMvOoQ-W6MlpHIDb1xqF3hvDYL7BvA3_eGOjTl2AmnYgbVlr77F8_7wUHK2qoxaD6xbdZFlI87-bG7JXaTE5z87Ll9sYa8erq3AXGj0vsWDK5gx1SQUF1tW4FWNti4TDCTQD5gMMLzH7MUaUnRNCC2BqLNQJVFwBNKJiVZeRC8SudjZsaBLNEc&__tn__=-R
