### ISSUE TITLE
integration with SSG?

### ISSUE THREAD

**Issue by ckot** [KidkArolis/jetpack#74]
Hi, my SPA is primarily showing/hiding/enabling/disabling bits of pre-generated html, which I'm generating with 11ty.  Would jetpack be able to use my generated index.html as the template for including the bundle(s) or would I be better off just including references to them in the templates which build my index.html or do custom webpack stuff rather than jetpack?

**Comment by KidkArolis** [comment]
That's an interesting question.

You could indeed try to point to your 11ty generated index.html using the `--html` option. And in there, use a bit of handlebars syntax to include all the right assets:

```hbs
{{#each assets.css}}
<link rel="stylesheet" href='{{{.}}}' />
{{/each}}

{{#if assets.runtime}}
<script type='text/javascript'>
{{{assets.runtime}}}
</script>
{{/if}}

{{#each assets.js}}
<script type='text/javascript' src='{{{.}}}' async></script>
{{/each}}
```

^ This is taken from the [default template](https://github.com/KidkArolis/jetpack/blob/bd5e84e2c6b2718365a4b452d78951d7d4ecf711/lib/template.hbs).

Alternatively, what jetpack does behind the scenes is it reads `dist/manifest.json` file to extract all the top level js/css to be included into the html, you could consider doing something similar: https://github.com/KidkArolis/jetpack/blob/bd5e84e2c6b2718365a4b452d78951d7d4ecf711/lib/options.js#L207-L251.

**Comment by ckot** [comment]
Cool beans.  Glad to hear it's unlikely I'll need to do custom webpack stuff anymore. While it might take a while before I have time to convert from my custom stuff to using jetpack with one of the configurations you propose above, I'm closing this now. as I'm confident enough now, based on what you've shown, that I **will** be able to migrate to jetpack at some point soon.
