### ISSUE TITLE
Default to `preact.h` instead of `Preact.h`?

### ISSUE THREAD

**Issue by KwanMan** [KidkArolis/jetpack#8]
Even though react convention is to import to capitalised `React`, on the preact docs examples, it imports to `preact` rather than `Preact`. Maybe default to that instead to align with their docs?

**Comment by KidkArolis** [comment]
Yeah, I think I'll switch it over, even though I'm personally really used to uppercasing it. It's configurable, so whatevs.

I might also pull this in in the future - it doesn't require for React/preact to be in scope, it auto requires it if needed. Though I wonder if that's dodgy.. more plugins isn't necessarily nice..

**Comment by KidkArolis** [comment]
tbh, most of the time people seem to do `import { h } from preact`. Cause also `h` is like a more universal jsx target pragma. Maybe I should do that, like `React.createElement` or fallback to `h`.

**Comment by KidkArolis** [comment]
Using `h` on master now.
