### ISSUE TITLE
Proxy configuration doesn't pass query string parameters

### ISSUE THREAD

**Issue by optinirr** [KidkArolis/jetpack#89]
It isn't hard to reproduce, simply create an endpoint in your back-end server that requires a query parameter, and configure jetpack like so: 
```
proxy: {
    '/api/*': 'http://some-backend'
  },
```

the code in lib/proxy.js is missing req.query being passed to reqOpt.path, will do a PR if one doesn't exist.

**Comment by optinirr** [comment]
PR https://github.com/KidkArolis/jetpack/pull/90

**Comment by KidkArolis** [comment]
Thanks! Released as 0.20.1 (note that previous stable version was 0.19.0, so you'll get the breaking change of PostCSS 8 with the 0.20.*).
